<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="Vistas.Formulario_web1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <div style="margin:2%;">
        <h2 style="text-align:center">
        Carrito de Compras
        </h2>
      
     
        <hr / style="margin:0px">
        <table style="width: 100%">
            <tr>
                <td> <h5>Cantidad de Productos</h5></td>
                <td><asp:Label ID="LbcantidadProductos" runat="server" Text="0" Font-Size="30px"></asp:Label></td>
            </tr>
        </table> 
        <hr /style="margin:0px">
    </div>
    <div class="d-flex justify-content-center mb-3">
        <asp:GridView ID="GvCarro" runat="server"  CssClass="table display"  Width="1061px" AutoGenerateDeleteButton="True" OnRowDeleting="GvCarro_RowDeleting" ></asp:GridView>
    </div> 
    <div style="display:flex; justify-content:space-around">
        <div>
        <asp:Button ID="BtnEliminarCarro" runat="server" Text="ELIMINAR CARRO" style="padding:8px; background-color:#EC7063;color:white; border-style:none; border-radius:5px; letter-spacing:2px; width:200px  " OnClick="BtnEliminarCarro_Click" />
        </div>
        <div>
         <asp:Button ID="BtnConfirmarCarro" runat="server" Text="CONFIRMAR COMPRA" style="padding:8px; background-color:#3498DB;color:white; border-style:none; border-radius:5px; letter-spacing:2px; width:200px" OnClick="BtnConfirmarCarro_Click" />
        </div>
    </div>

  <div style="margin:2%;  ">
        <hr />
        <table style="width: 100%">
            <tr>
                <td> <h1>Total a Pagar</h1></td>
                <td><asp:Label ID="Lbmonto" runat="server" Text="$0.00" Font-Size="30px"></asp:Label></td>
            </tr>
        </table> 
        <hr />
  </div>
</asp:Content>
