<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="Vistas.Formulario_web1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   
    


    
 <div style="margin:2%;">
        <h2 style="text-align:center">
        Carrito de Compras
        </h2>
      
     
        <hr / style="margin:0px">
        <table style="width: 100%">
            <tr>
                <td> <h5>Cantidad de Productos</h5></td>
                <td><asp:Label ID="LbcantidadProductos" runat="server" Text="0" Font-Size="30px"></asp:Label></td>
            </tr>
        </table> 
        <hr /style="margin:0px">
 


    </div>
    <div style=" display:flex; margin:2%">
        <%--  <asp:GridView ID="GridView2" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" Width="1061px" AutoGenerateDeleteButton="True" AllowPaging="True" PageSize="5">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="IdProducto" HeaderText="IdProducto" SortExpression="IdProducto" />
                <asp:BoundField DataField="NombreProducto" HeaderText="NombreProducto" SortExpression="NombreProducto" />
                <asp:BoundField DataField="IdCategoría" HeaderText="IdCategoría" SortExpression="IdCategoría" />
                <asp:BoundField DataField="PrecioUnidad" HeaderText="PrecioUnidad" SortExpression="PrecioUnidad" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>--%>

        <asp:GridView ID="GridView1" runat="server"  CssClass="table display"  Width="1061px" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" >
        <Columns>
            <asp:TemplateField HeaderText="Id">
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("id") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Nombre">
                <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Eval("nombre") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Descripcion">
                <ItemTemplate>
                    <asp:Label ID="Label3" runat="server" Text='<%# Eval("descripcion") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Precio">
                <ItemTemplate>
                    <asp:Label ID="Label4" runat="server" Text='<%# Eval("precio") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        
        </Columns>
    </asp:GridView>

    </div>
    
    <div style="display:flex; justify-content:space-around">
        <div>
        <asp:Button ID="Button1" runat="server" Text="ELIMINAR CARRO" style="padding:8px; background-color:#EC7063;color:white; border-style:none; border-radius:5px; letter-spacing:2px; width:200px  " OnClick="Button1_Click" />
        </div>
        <div>
         <asp:Button ID="btconfir" runat="server" Text="CONFIRMAR COMPRA" style="padding:8px; background-color:#3498DB;color:white; border-style:none; border-radius:5px; letter-spacing:2px; width:200px" />
        </div>
    </div>

  <div style="margin:2%;  ">
        <hr />
        <table style="width: 100%">
            <tr>
                <td> <h1>Total a Pagar</h1></td>
                <td><asp:Label ID="Lbmonto" runat="server" Text="$0.00" Font-Size="30px"></asp:Label></td>
            </tr>
        </table> 
        <hr />
    </div>



    
    
    <!-- FROTERA-->
    <%--<div class="card-body">
    <asp:GridView ID="GridView1" runat="server"  CssClass="table display" >
        <Columns>
            <asp:TemplateField HeaderText="Id">
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("id") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Nombre">
                <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Eval("nombre") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Descripcion">
                <ItemTemplate>
                    <asp:Label ID="Label3" runat="server" Text='<%# Eval("descripcion") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Precio">
                <ItemTemplate>
                    <asp:Label ID="Label4" runat="server" Text='<%# Eval("precio") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        
        </Columns>
    </asp:GridView>
       </div>--%>
</asp:Content>
